In [1]:
#creating blank array
import numpy as np
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
#creating array with predefined data
arr = np.array([1,2,3])
print(arr)


[1 2 3]


In [3]:
#creating array with pattern specific data
arr1=np.arange(start=1, stop=10, step=3)
arr2 = np.linspace(10, 20, 5)  
print(arr1)
print(arr2)

[1 4 7]
[10.  12.5 15.  17.5 20. ]


In [6]:
#slicing the array
arr=np.arange(start=1, stop=30, step=3)
sliced_array1 = arr[1:10]
sliced_array2 = arr[:10]
sliced_array3 = arr[2:]
sliced_array4 = arr[1:10:2]
print(sliced_array1)
print(sliced_array2)
print(sliced_array3)
print(sliced_array4)


[ 4  7 10 13 16 19 22 25 28]
[ 1  4  7 10 13 16 19 22 25 28]
[ 7 10 13 16 19 22 25 28]
[ 4 10 16 22 28]


In [10]:
#updating the array
arr=np.arange(start=1, stop=30, step=2)
print("Before update :",arr)
arr[3] = 91
print("After update :",arr)


Before update : [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
After update : [ 1  3  5 91  9 11 13 15 17 19 21 23 25 27 29]


In [16]:
#shape
arr=np.arange(start=1, stop=30, step=2)
print("Array : ",arr)
reshaped_array = np.reshape(arr, (3,5))
print("reshaped_array :\n ",reshaped_array)

#‘F’ means to flatten in column-major
flattened_array = reshaped_array.flatten('F')
print("flattened_array :\n" ,flattened_array)


Array :  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
reshaped_array :
  [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]
flattened_array :
 [ 1 11 21  3 13 23  5 15 25  7 17 27  9 19 29]


In [18]:
#looping over the array
arr = np.arange(start=1, stop=30, step=2).reshape((3,5))
for element in arr:
   print(element)  

[1 3 5 7 9]
[11 13 15 17 19]
[21 23 25 27 29]


In [23]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [25]:
#reading files in numpy
data = np.genfromtxt('/content/gdrive/MyDrive/data.csv', delimiter= ' ', dtype=str)
print(data)

['Name,City,certificate' 'Jeel,suart,AWS' 'Meet,ahemdabad,REDHAT'
 'Aniket,jamnagar,CEH' 'Sharad,navsari,AWS' 'Bhavdip,Rajkot,AAA']


In [20]:
#using numpy for matrix multiplications
import numpy as np
import time

# Generate two random 1000 x 1000 matrices
matrix_a = np.random.rand(1000, 1000)
matrix_b = np.random.rand(1000, 1000)

start_time = time.time()
result = np.dot(matrix_a, matrix_b)
end_time = time.time()

time = end_time - start_time

print(f"NumPy matrix multiplication took {time:.6f} seconds.")

NumPy matrix multiplication took 0.070293 seconds.


In [22]:
import time
import random
# Generate two random 1000 x 1000 matrices
matrix_a = [[random.random() for j in range(1000)] for i in range(1000)]
matrix_b = [[random.random() for j in range(1000)] for i in range(1000)]

start_time = time.time()
result = [[0 for j in range(1000)] for i in range(1000)]

for i in range(1000):
    for j in range(1000):
        for k in range(1000):
            result[i][j] += matrix_a[i][k] * matrix_b[k][j]


end_time = time.time()
time = end_time - start_time

print(f"List matrix multiplication took {time:.6f} seconds.")


List matrix multiplication took 433.126120 seconds.
